name: Update Homebrew casks

on:
  schedule:
    - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  update-casks:
    runs-on: macos-latest
    steps:
      - name: Update Homebrew casks
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          tap: bsiegel/tap
          livecheck: true
